spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    static-path-pattern: classpath:/static/**
  #redis配置
  redis:
    host: 127.0.0.1
    port: 6666
    maxTotal: 200
    pool:
      config:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: 10000
    timeout: 5000
    password: 666666
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

logging:
  level:
    root: debug
    com.wb: debug
  file: log/backend-pro.log

server:
  port: 80

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #  别名包扫描
  type-aliases-package: com.wb.entity
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

ftp:
  host: "127.0.0.1"
  port: 21
  username: "ftpuser"
  password: "123456"
  basePath: "/usr/local/myblog"
  filePath: "/img"